AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3-prueba-aws/71abcb3c04882d3caf12c8343e6c7d9b
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user
            Method: post
    Metadata:
      SamResourceId: CreateUserFunction
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3-prueba-aws/f5d035bf0293671eb613a2d76607a650
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: get
    Metadata:
      SamResourceId: GetUserFunction
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3-prueba-aws/4b76e735ea5e5f66d40c12158e7a5461
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/
            Method: get
    Metadata:
      SamResourceId: GetUsersFunction
  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3-prueba-aws/91808cd5007933905df62c9ad3235945
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        UpdateUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: put
    Metadata:
      SamResourceId: UpdateUserFunction
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3-prueba-aws/27b860d18a4e12c5cca48e5848eac254
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: delete
    Metadata:
      SamResourceId: DeleteUserFunction
Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
