name: Selenium Tests

on: 
  push:
    branches: 
      - master  # Cambiado de main a master
  pull_request:
    branches: 
      - master  # Cambiado de main a master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install selenium
        pip install pytest
        # Aquí puedes añadir cualquier otra dependencia que necesites
    
    - name: Download WebDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
    
    - name: Run Selenium Tests
      run: python test_selenium.py  # Asegúrate de que este comando sea correcto según tu estructura de archivos y directorios
