name: Selenium Tests

on: 
  push:
    branches: 
      - master # Asegúrate de que esto coincide con el nombre de tu rama principal
  pull_request:
    branches: 
      - master # Asegúrate de que esto coincide con el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install selenium
        pip install pytest
        # Aquí puedes añadir cualquier otra dependencia que necesites
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version
    
    - name: Get Chrome version
      run: echo "CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9.]+' | head -1)" >> $GITHUB_ENV

    - name: Install compatible ChromeDriver
      run: |
        CHROME_MAJOR_VERSION=$(echo "${{ env.CHROME_VERSION }}" | cut -d'.' -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip -o chromedriver_linux64.zip -d ./chromedriver
        sudo mv chromedriver/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

        
    - name: Run Selenium Tests
      run: python test_selenium.py
