name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install pytest

      - name: Check Chrome version
        id: check_chrome_version
        run: |
          chrome_version=$(google-chrome --version | grep -oP '(?<=Chrome/)\d+(.\d+)*')
          echo "::set-output name=chrome_version::$chrome_version"
        shell: bash

      - name: Download ChromeDriver (dynamic)
        run: |
          chrome_version=${{ steps.check_chrome_version.outputs.chrome_version }}
          curl -Lo chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$chrome_version/chromedriver_linux64.zip"
        shell: bash

      - name: Extract ChromeDriver
        run: unzip -o chromedriver_linux64.zip -d ${{ github.workspace }}

      - name: Move ChromeDriver to PATH
        run: |
          sudo mv ${{ github.workspace }}/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium Tests
        run: python test_selenium.py
