name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install pytest

      - name: Check Chrome version
        id: check_chrome_version
        run: |
          # Get Chrome version on Ubuntu-based systems
          chrome_version=$(google-chrome --version | grep -oP '(?<=Chrome/)\d+(.\d+)*')
          echo "Detected Chrome version: $chrome_version"
          # Store the version in a reusable output variable

      - name: Download ChromeDriver (dynamic)
        uses: actions/checkout@v2  # Reuse checkout action for flexibility
        with:
          url: |  # Construct the URL dynamically based on Chrome version
            https://chromedriver.storage.googleapis.com/${chrome_version}/chromedriver_linux64.zip
          path: ${{ github.workspace }}  # Download to workflow workspace

      - name: Extract ChromeDriver
        run: unzip -o ${{ github.workspace }}/chromedriver_linux64.zip -d ${{ github.workspace }}

      - name: Move ChromeDriver to PATH
        run: |
          sudo mv ${{ github.workspace }}/chromedriver/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium Tests
        run: python test_selenium.py
