name: Selenium Tests

on: 
  push:
    branches: 
      - master # Cambiado de main a master
  pull_request:
    branches: 
      - master # Cambiado de main a master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install selenium
        pip install pytest
        # Aquí puedes añadir cualquier otra dependencia que necesites
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Get Chrome version
      id: chrome-version
      run: |
        echo "CHROME_VERSION=$(google-chrome --version)" >> $GITHUB_ENV

    - name: Install compatible ChromeDriver
      run: |
        CHROME_VERSION=${{ env.CHROME_VERSION }}
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%%.*}")
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d chromedriver
        sudo mv chromedriver/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version
        
    - name: Run Selenium Tests
      run: python test_selenium.py
